apiVersion: v1
kind: Service
metadata:
  name: svc-ocp-metrics-selector
  labels:
    app: ocp-metrics-selector
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: ocp-metrics-selector
